### ISSUE TITLE
Work with lasagne 0.2 dev only

### ISSUE THREAD

**Issue by TobyOoO** [ciaua/clip2frame#2]
scripts/test_model.frame.py works with lasagne 0.2 dev only, otherwise the following error may occur.
You may consider to specify this information on README, or simply refer it in your requirements.txt .
`
Traceback (most recent call last):
  File "test_model.frame.py", line 84, in <module>
    network_type, n_scales, network_options
  File "build/bdist.linux-x86_64/egg/clip2frame/utils.py", line 217, in make_network_multiscale_test
  File "build/bdist.linux-x86_64/egg/clip2frame/network_design.py", line 176, in fcn_gaussian_multiscale
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/merge.py", line 29, in __init__
    super(ConcatLayer, self).__init__(incomings, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'cropping'
`

**Comment by exeex** [comment]
to install the dependcies in a conda env:

`conda install -c jaikumarm theano=0.9.0.dev4 `


`pip install scikit-learn==0.18.1`

```
git clone https://github.com/Lasagne/Lasagne.git
cd Lasagne
python setup.py install
```
It works on my Ubuntu  16.04
